on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

name: 'Daily CI Tests'

jobs:
  daily_tests_job:
    timeout-minutes: 60
    runs-on: self-hosted
    name: 'All tests'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: false

      - run: |
          ${{ steps.setup-python.outputs.python-path }} -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          echo $VIRTUAL_ENV
          python -m pip install --upgrade pip
          python -m pip install -r $GITHUB_WORKSPACE/requirements.txt $GITHUB_WORKSPACE/.
          pytest -n auto --import-mode=append
