on: [workflow_dispatch, push]

name: 'Quick CI Tests'

jobs:
  self_hosted_tests:
    timeout-minutes: 15
    runs-on: self-hosted
    name: 'Tool-based tests'
    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          echo $VIRTUAL_ENV
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt $GITHUB_WORKSPACE/.
          pytest -n 4 --import-mode=append -m "eda and quick"

  python_test_job:
    timeout-minutes: 15
    runs-on: ${{ matrix.version.os }}
    name: 'Pure Python tests'
    strategy:
      fail-fast: false
      matrix:
        version:
          - {python: "3.6", os: "ubuntu-20.04"}
          - {python: "3.7", os: "ubuntu-latest"}
          - {python: "3.8", os: "ubuntu-latest"}
          - {python: "3.9", os: "ubuntu-latest"}
          - {python: "3.10", os: "ubuntu-latest"}
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install graphviz

      - name: Set up Python ${{ matrix.version.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version.python }}

      - run: |
          pip install $GITHUB_WORKSPACE/.[test]
          pytest --import-mode=append -m "not eda"
