name: 'Python CI Tests'

on:
  workflow_dispatch:
  push:

jobs:
  python_test_job:
    timeout-minutes: 15
    runs-on: ${{ matrix.version.os }}
    name: 'Pure Python tests'
    strategy:
      fail-fast: false
      matrix:
        version:
          - {python: "3.8", os: "ubuntu-latest"}
          - {python: "3.9", os: "ubuntu-latest"}
          - {python: "3.10", os: "ubuntu-latest"}
          - {python: "3.11", os: "ubuntu-latest"}
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install graphviz

      - name: Set up Python ${{ matrix.version.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version.python }}
          cache: pip

      - name: Run Python tests
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[test]
          pytest -n auto --import-mode=append -m "not eda" --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          name: codecov-${{ matrix.version.python }}
          verbose: true
